[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_dir_name }}"
description = "TODO write description or delete"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
authors = [{ name = "nikkie", email = "takuyafjp+develop@gmail.com" }]
keywords = ["TODO", "write", "keywords"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-randomly",
{%- if cookiecutter.use_taskipy == "yes" %}
    "taskipy",
    "autoflake",
    "pyupgrade",
    "black",
    "isort",
    "flake8",
    "mypy",
{%- endif %}
]

[project.urls]
Repository = "TODO write repository URL"

[tool.setuptools.dynamic]
version = { attr = "{{ cookiecutter.package_name }}.__version__" }

{%- if cookiecutter.use_taskipy == "yes" %}
[tool.taskipy.tasks]
pre_test = "task format"
test = "pytest -v"
post_test = "task check"
format = "task format_autoflake && task format_pyupgrade && task format_black && task format_isort"
format_autoflake = "autoflake --in-place --remove-all-unused-imports $(find src tests -name '*.py') setup.py"
format_pyupgrade = "pyupgrade $(find src tests -name '*.py') setup.py"
format_black = "black -l 79 src tests setup.py"
format_isort = "isort --profile black -l 79 src tests setup.py"
check = "task check_flake8 && task check_mypy"
check_flake8 = "flake8 src tests"
check_mypy = "mypy src tests"
{%- endif %}
